# Generated by Django 4.1.1 on 2022-11-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0003_referencesauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=40, verbose_name='Book')),
                ('img', models.ImageField(upload_to='', verbose_name='Book cover')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default='null', max_length=40, on_delete=django.db.models.deletion.PROTECT, to='references.referencesauthor')),
                ('currenсy', models.ForeignKey(default='null', max_length=20, on_delete=django.db.models.deletion.PROTECT, to='references.referencescurrenсy')),
                ('genre', models.ForeignKey(default='null', max_length=40, on_delete=django.db.models.deletion.PROTECT, to='references.referencesgenre')),
            ],
        ),
    ]
