# Generated by Django 4.1.1 on 2022-11-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsbooks',
            name='img',
        ),
        migrations.AddField(
            model_name='goodsbooks',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Book cover'),
        ),
    ]
