# Generated by Django 4.1.1 on 2022-12-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_referencesauthor'),
        ('goods', '0003_alter_goodsbooks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbooks',
            name='genre',
            field=models.ForeignKey(default='null', max_length=40, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='references.referencesgenre'),
        ),
    ]
