# Generated by Django 4.1.1 on 2022-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencescurrenсy',
            name='name',
            field=models.CharField(default='null', max_length=20, verbose_name='Currenсy'),
        ),
    ]
