# Generated by Django 4.1.1 on 2022-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_referencescurrenсy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=40, verbose_name='Author')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
