# Generated by Django 4.1.1 on 2022-11-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodsbooks_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookinCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodsbooks', verbose_name='Book in a cart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Book', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
