# Generated by Django 4.1.1 on 2022-12-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='orders.cart', verbose_name='Cart'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In progress', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('adress', models.CharField(max_length=100, verbose_name='Adress')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('info', models.TextField(max_length=500, verbose_name='Info')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
