# Generated by Django 4.1.1 on 2022-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_bookincart_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Sended', 'Sended'), ('Done', 'Done')], default='In progress', max_length=20, verbose_name='Status'),
        ),
    ]
